version: '3.4'
services:
  web-client-mentors-diary:
    container_name: web-client-mentors-diary
    build: 
      context: ../
      dockerfile: ./MentorsDiary.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8092:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock