version: '3.4'
services:
  db-mentors-diary:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: MentorsDiary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweASD!@#
    ports: 
      - "5440:5432" 
    networks:
      - mentors-diary-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api-mentors-diary:
    container_name: api-mentors-diary
    build: 
      context: ../
      dockerfile: ./MentorsDiary.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mentors-diary-dev
    ports:
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db-mentors-diary
volumes:
  postgres-data:
networks:
  mentors-diary-dev:
    driver: bridge